const empireList = [
    "Groupe Bolloré",
    "Gameloft",
    "Bigben Interactive",
    "Mediobanca",
    "CSELT",
    "TIM (Telecom Italia)",
    "MFE (MediaForEurope)",
    "Ubisoft",
    "Universal Music Group",
    "Telefonica",
    "Socfinaf",
    "Amazon",
    "Socfin",
    "Studiocanal",
    "Automatic Systems",
    "Groupe Canal+",
    "Havas Group",
    "Louis Hachette Group",
    "Vivendi",
    "Blue Solutions",
    "Plantations des Terres Rouges",
    "Blue Systems",
    "Bollore Energy",
    "Africa Global Logistics",
    "Compagnie du Cambodge",
    "FL Entertainment",
    "MultiChoice",
    "Alterfood",
    "DPL-Lorient",
    "SDLP-La Rochelle",
    "DPSPC-Tours",
    "EPV-Valenciennes",
    "EPM-Mulhouse",
    "Raffinerie du Midi",
    "DRPC (Dépôt Rouen Petit-Couronne)",
    "TAR-Zurich",
    "Sasma-Genève",
    "Calpam",
    "Izipure",
    "Viaplay",
    "Viu",
    "Orange Studio",
    "OCS",
    "Lagardère Publishing",
    "Hachette Livre",
    "Lagardère Travel Retail",
    "Travel Essentials",
    "Duty Free & Fashion",
    "Foodservice",
    "Havas Creative Group",
    "Havas Media Group",
    "Havas Health & You",
    "Prisma Media",
    "Capital",
    "Femme actuelle",
    "Geo",
    "Télé Loisirs",
    "Olympia Production",
    "U Live",
    "Vivendi Village",
    "Olympia",
    "See Tickets",
    "Dailymotion",
    "Capitol Music Group",
    "Interscope Geffen A&M",
    "Republic Records",
    "Island Records",
    "Motown Records",
    "Def Jam Recordings",
    "Universal Music Group Nashville",
    "Universal Music Latin Entertainment",
    "Polydor Records",
    "Blue Note Records",
    "Decca",
    "Deutsche Grammophon",
    "Verve Label Group",
    "Capitol Studios",
    "Abbey Road",
    "Bravado",
    "Blue",
    "Bluebus",
    "Bluestorage",
    "Bollore Innovative Thin Films",
    "Packaging films",
    "Dielectric films",
    "EASIER",
    "Track & Trace",
    "Smart City Platform",
    "Indestat",
    "Polyconseil",
    "Smart Mobility",
    "Nacon",
    "Cyanide",
    "Eko Software",
    "Kylotonn",
    "Spiders",
    "Passtech Games",
    "Neopica",
    "Big Ant Studios",
    "Crea-ture Studios",
    "Ishtar Games",
    "Daedalic Entertainment",
    "Midgar Studio",
    "Rogue Factor",
    "Big Bad Wolf Studio",
    "Bollore Telecoms",
    "CNews",
    "Direct 8",
    "Direct Star",
    "Direct Azur",
    "Direct Soir",
    "Direct Femme",
    "Direct Sport",
    "Radio Nouveaux Talents",
    "Le Mac Mahon",
    "Sorento",
    "Buzzman",
    "CA Sports",
    "Olivetti",
    "Telecom Italia Sparkle",
    "Infrastrutture Wireless Italiane",
    "Telecom Italia Truste Technologies",
    "TIM Brasil",
    "Telecom Italia San Marino",
    "Telecom Italia Capital",
    "Telecom Italia Finance",
    "Tesly",
    "Les Deux Royaumes",
    "Ubisoft Motion Pictures",
    "Polar Music",
    "The Kushner-Locke Compagny",
    "Venkow Records",
    "Nu Image",
    "Virgin EMI Records",
    "EMI Records",
    "Universal Music Taiwan",
    "Priority Records",
    "Young Money Entertainment",
    "Interscope Records",
    "Capitol Records",
    "Mercury Records",
    "Casablanca Music",
    "Universal Music Operations",
    "Eccentric music",
    "Virgin Records",
    "SDKT Entertainment",
    "Universal Music Argentina",
    "UMG Recordings",
    "Universal Music Sdn",
    "Mass Appeal Records",
    "Universal Music GmbH",
    "Cash Money Records",
    "Vertigo Records",
    "Capitol Music",
    "Eagle Rock Entertainment",
    "Decca Records",
    "Universal Music France",
    "Universal Music Hong Kong",
    "MCA Records",
    "EMI Japan",
    "Flip Records",
    "Universal Music Japan",
    "Universal Music Malaysia",
    "Verve Records",
    "Universal Music Spain",
    "London Records",
    "Musidisc",
    "Roc-A-Fella Records",
    "Shady Records",
    "Universal Music Romania",
    "Ruff Ryders Entertainment",
    "Amaru Entertainment",
    "Universal Music Entreprises",
    "EmArcy Records",
    "Universal Music Portugal",
    "Universal Music Australia",
    "Universal Music Indonesia",
    "Telefonica Moviles",
    "Vivo",
    "Telefonica O2",
    "Socfinasia",
    "Socfinde",
    "PNS",
    "STP Invest",
    "SAFA",
    "Bereby Finances",
    "Socapalm",
    "Safacam",
    "Automatic Systems SAS-France",
    "Automatic Systems Espanola SAU",
    "Automatic Systems Equipment UK",
    "Automatic Systems America",
    "Automatic Control Systems",
    "Suzhou Automatic Systems Entrance Control",
    "Havas Creative",
    "Havas Media",
    "Havas Worldwide",
    "BETC",
    "Arnold Worldwide",
    "Havas Edge",
    "Arena Media",
    "Lagardère",
    "Hachette Book Group",
    "Hachette Jeunesse",
    "Orion Publishing Group",
    "Armand Colin",
    "Grasset",
    "Hatier",
    "Larousse",
    "Fayard",
    "JC Lattès",
    "Calmann-Levy",
    "Dunod",
    "Relay",
    "Lagardère News",
    "Le Journal du Dimanche",
    "Elle",
    "Lagardère Radio",
    "Europe 1",
    "Europe 2",
    "RFM",
    "Lagardère Live Entertainment",
    "Casino de Paris",
    "Arkéa Arena",
    "Arena du Pays d'Aix",
    "Folies Bergère",
    "Lagardère Paris Racing",
    "Prima",
    "Voici",
    "Gala",
    "Geo (France)",
    "Ca m'intéresse",
    "National Geographic (France)",
    "Neon",
    "Capital",
    "Management",
    "Harvard Business Review France",
    "Simone",
    "Banijay",
    "Vivendi Ticketing",
    "InfoConcert",
    "Zepass",
    "Théâtre de L'Oeuvre",
    "Vivendi Sports",
    "CanalOlympia",
    "CanalOlympia Wologuèdé",
    "Le Petit Olympia",
    "Canal Factory",
    "Mediaset",
    "Prisa",
    "BAC Films",
    "CA Brive",
    "C8",
    "CStar",
    "MyCanal",
    "Canal VOD",
    "Canal+ Brand solutions",
    "Canal+ Cinéma",
    "Canal+ Sport",
    "Canal+ Séries",
    "Canal+ Family",
    "Canal+ Décalé",
    "K+ Vietnam",
    "Canal+ International",
    "Canal+",
    "Canal+ Calédonie",
    "Canal+ Caraïbes",
    "Canal+ Réunion",
    "Canal+ Afrique",
    "Thema",
    "Canal+ Distribution",
    "Canal+ Thématiques Sport",
    "Ciné+",
    "Planète+",
    "Télétoon+",
    "Piwi+",
    "Foot+",
    "Comédie+",
    "Infosport+",
    "Season",
    "Olympia TV",
    "Canal+ Myanmar",
    "M7",
    "Télésat",
    "TV Vlaanderen",
    "Canal Digitaal",
    "Focus Sat",
    "UPC Direct",
    "Copyrights Group",
    "Cuisine Actuelle",
    "Miaou Magazine",
    "Télé 2 semaines",
    "TV Grandes Chaines",
    "Les clés de mon énergie",
    "Mortelle Adèle",
    "Dailymotion",
    "Canal+ France",
    "SPI International",
    "FilmBox International",
    "MediaBox Broadcasting International",
    "FilmBox+",
    "Canal+ Luxembourg",
    "Canal+ Austria",
    "Canal+ République Tchèque & Slovaquie",
    "Canal+ Pays-Bas",
    "Canal+ Action",
    "Kino Polska Group",
    "Stopklatka",
    "Canal+ Polska",
    "Planète+ Canada",
    "Studiocanal TV Canada",
    "Théma America",
    "Viaplay Group",
    "Viu International",
    "Canal+ Maurice",
    "Canal+ Suisse",
    "Canal+ Polynésie",
    "Canal+ Rights",
    "Canal+ Tech",
    "Canal+ Thématiques",
    "Mezzo",
    "Ciné+ OCS",
    "Planète+ Crime",
    "Sport+",
    "Nulle Part Ailleurs Production",
    "Financière Moncey",
    "Forestière Equatoriale",
    "Compagnie des Tramways de Rouen",
    "Financière de l'Odet",
    "Hachette Education",
    "Foucher",
    "Deux Coqs D'Or",
    "La Maison Hachette Pratique",
    "Marabout",
    "E/P/A",
    "Grasset",
    "Hachette Livre International",
    "Hachette Illustré",
    "La Bibliothèque Rose et Verte",
    "Chêne",
    "Les editions Albert René",
    "Le Livre de Poche",
    "Audiolib",
    "Gautier Languereau",
    "Hazan",
    "Hatier jeunesse",
    "edition didier",
    "Rageot",
    "Le livre de poche jeunesse",
    "hachette romans",
    "pika edition",
    "Groupe Alexandre Hatier",
    "lelivrescolaire",
    "stock",
    "Hachette Jeunesse Collection Disney",
    "Hachette Tourisme",
    "Headline",
    "Hachette Australia",
    "John Catt",
    "Laurence King",
    "Quercus",
    "Hachette Children's Group",
    "Hachette Learning",
    "Litte Brown Book Group",
    "Hodder & Stoughton",
    "John Murray Press",
    "Kero",
    "Edition n°1",
    "Orbit",
    "Hachette Français langue etrangere",
    "Istra",
    "Harrap's",
    "Dessain & Tolra",
    "Nouvelles Energies",
    "Comet",
    "Hachette Heroes",
    "Le Lotus et l'éléphant",
    "Les insolentes",
    "Black Lab",
    "Marabulles",
    "La Belle Etoile",
    "Grasset Jeunesse",
    "Pluriel",
    "Mazarine",
    "Pauvert",
    "Mille et une nuits",
    "La plage",
    "Bragelonne",
    "Le Masque",
    "Les Editions Des 2 Terres",
    "La Grenade",
    "Nouveaux Jours",
    "BMR",
    "HLAB",
    "Didier Jeunesse",
    "Didier Français langue etrangere",
    "Kwyk",
    "Hachette enfants",
    "Headline Review",
    "Eternal Romance",
    "Tinder Press",
    "Wildfire",
    "Headline Home",
    "Lothian Children's Books",
    "MacLehose Press Quercus - London",
    "Jo Fletcher Books",
    "Riverrun",
    "Franklin Watts",
    "Hodder Children's Books",
    "Orchard Books",
    "Wayland",
    "Orion Children's Books",
    "Litte Brown Book Group For Young Readers",
    "Enid Blyton Entertainment",
    "Quercus Children's Books",
    "Pat-a-Cake",
    "Wren & Rook",
    "Illuminate",
    "Fleet",
    "Dialogue Books",
    "Little Brown",
    "Abacus",
    "Piatkus",
    "Sphere Fiction",
    "Virago",
    "Atom",
    "Corsair",
    "Blackfriars",
    "Hachette Audio UK",
    "Constable",
    "Robinson",
    "Basic Books",
    "Sceptre",
    "Coronet",
    "Yellow Kite",
    "Two Roads",
    "Hodder Faith",
    "John Murray Learning",
    "Nicholas Brealey Publishing",
    "Jessica Kingsley Publishers",
    "Bookouture",
    "White Rabbit",
    "Orion Dash",
    "Orion Fiction",
    "Gollancz",
    "Weidenfeld & Nicolson",
    "Seven Dials",
    "Orion Spring",
    "Trapeze",
    "Orion Audio",
    "Moa",
    "Paperblanks",
    "Hachette India",
    "Hachette New Zealand",
    "Monoray",
    "Endeavour",
    "Cassell Illustrated",
    "Gaia",
    "Godsfield Press",
    "Hamlyn",
    "Miller's",
    "Mitchell Beazley",
    "Philip's",
    "Bounty Books",
    "Pyramid",
    "Spruce",
    "Ilex",
    "Aster",
    "Kyle Books",
    "Summersdale",
    "Octopus Publishing",
    "Hachette Ireland",
    "Hachette Audio",
    "Redhook",
    "Hachette Nashville",
    "FaithWords",
    "Center Street",
    "Worthy",
    "Voracious",
    "Back Bay Books",
    "Jimmy Patterson",
    "Little Brown Spark",
    "Mulholland Books",
    "Perseus Books",
    "Avalon Travel",
    "PublicAffairs",
    "Hachette Books",
    "Running Press",
    "Grand Central Publishing",
    "Twelve",
    "Forever",
    "Forever Yours",
    "LB Kids",
    "Poppy",
    "Workman Publishing",
    "Anaya Educacion",
    "Barcanova Editorial",
    "Grupo Editorial Patria",
    "Bruno",
    "Hachette Heroes e Infantil",
    "Salvat",
    "Ediciones Piramide",
    "Anaya Multimedia",
    "Alianza Editorial",
    "Anaya ELE",
    "Anaya Touring",
    "Xerais",
    "Contraluz",
    "Petaletras",
    "Edelsa",
    "VOX",
    "Tecnos",
    "Alianza de Novelas",
    "Faeris",
    "Algaida Editores",
    "Anaya Infantil y Juventil",
    "Ediciones Larousse Mexique",
    "Catedra",
    "Boveda",
    "Hachette Antoine",
    "NEI-Ceda",
    "Librairie Nationale",
    "Blackrock Games",
    "Gigamic",
    "Hiboutatillus",
    "Randolph",
    "Catch Up Games",
    "Studio H",
    "La Boite De Jeu",
    "Hachette Boardgames",
    "Funny Fox",
    "Sorry We Are French",
    "Le Scorpion Masqué",
    "Hachette Partworks",
    "Editorial Salvat",
    "Hachette Collections",
    "Hachette Kollektsia",
    "Hachette Collections Japan",
    "Kolekcja Hachette",
    "Hachette Fascicoli",
    "Calmann-Levy",
    "Hachette Livre Distribution",
    "Comercial Grupo Anaya",
    "Dilibel",
    "DiffuLivre",
    "Bookpoint",
    "Alliance distribution service",
    "Hachette Collections",
    "Hachette UK Distribution",
    "Lightning Source France"
];
